# Generated by Django 5.2.6 on 2025-09-27 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('visibility', models.CharField(choices=[('public', 'Público'), ('followers', 'Somente seguidores')], default='public', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('in_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_replies', to='posts.post')),
                ('quoted_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_by', to='posts.post')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='posts_post_created_183a3b_idx'), models.Index(fields=['author', '-created_at'], name='posts_post_author__f8ea20_idx')],
            },
        ),
    ]
