name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install UV
      run: pip install uv

    - name: Setup backend
      working-directory: ./backend
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install -e .

    - name: Lint
      working-directory: ./backend
      run: |
        source .venv/bin/activate
        ruff check .
        ruff format --check .

    - name: Test
      working-directory: ./backend
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        SECRET_KEY: test-secret-key
      run: |
        source .venv/bin/activate
        python manage.py migrate --run-syncdb
        pytest